"use client";

import { useState, useCallback } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Plus, Trash2 } from "lucide-react";
import CopyButton from "./CopyButton";

interface RobotsTxtGeneratorProps {
  t: Record<string, unknown>;
}

interface RobotRule {
  id: string;
  userAgent: string;
  allow: string[];
  disallow: string[];
}

export default function RobotsTxtGenerator({ t }: RobotsTxtGeneratorProps) {
  const common = t.common as Record<string, string>;
  const toolT = (t.tools as Record<string, Record<string, string>>)[
    "robots-txt-generator"
  ];

  const [rules, setRules] = useState<RobotRule[]>([
    { id: "1", userAgent: "*", allow: [], disallow: [] }
  ]);
  const [sitemap, setSitemap] = useState("");
  const [crawlDelay, setCrawlDelay] = useState("");
  const [output, setOutput] = useState("");

  const addRule = useCallback(() => {
    setRules(prev => [
      ...prev,
      { id: Date.now().toString(), userAgent: "*", allow: [], disallow: [] }
    ]);
  }, []);

  const removeRule = useCallback((id: string) => {
    setRules(prev => prev.filter(r => r.id !== id));
  }, []);

  const updateUserAgent = useCallback((id: string, value: string) => {
    setRules(prev => prev.map(r => r.id === id ? { ...r, userAgent: value } : r));
  }, []);

  const addPath = useCallback((id: string, type: "allow" | "disallow") => {
    setRules(prev => prev.map(r => {
      if (r.id === id) {
        return {
          ...r,
          [type]: [...r[type], ""]
        };
      }
      return r;
    }));
  }, []);

  const updatePath = useCallback((id: string, type: "allow" | "disallow", index: number, value: string) => {
    setRules(prev => prev.map(r => {
      if (r.id === id) {
        const newPaths = [...r[type]];
        newPaths[index] = value;
        return { ...r, [type]: newPaths };
      }
      return r;
    }));
  }, []);

  const removePath = useCallback((id: string, type: "allow" | "disallow", index: number) => {
    setRules(prev => prev.map(r => {
      if (r.id === id) {
        return {
          ...r,
          [type]: r[type].filter((_, i) => i !== index)
        };
      }
      return r;
    }));
  }, []);

  const generateRobotsTxt = useCallback(() => {
    let result = "# robots.txt generated by PureKit.dev\n\n";

    rules.forEach(rule => {
      result += `User-agent: ${rule.userAgent}\n`;
      
      rule.disallow.forEach(path => {
        if (path.trim()) {
          result += `Disallow: ${path}\n`;
        }
      });
      
      rule.allow.forEach(path => {
        if (path.trim()) {
          result += `Allow: ${path}\n`;
        }
      });

      if (crawlDelay && rule.userAgent !== "*") {
        result += `Crawl-delay: ${crawlDelay}\n`;
      }

      result += "\n";
    });

    if (sitemap.trim()) {
      result += `Sitemap: ${sitemap.trim()}\n`;
    }

    setOutput(result);
  }, [rules, sitemap, crawlDelay]);

  const handleClear = useCallback(() => {
    setRules([{ id: "1", userAgent: "*", allow: [], disallow: [] }]);
    setSitemap("");
    setCrawlDelay("");
    setOutput("");
  }, []);

  const handleDownload = useCallback(() => {
    if (!output) return;
    const blob = new Blob([output], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "robots.txt";
    a.click();
    URL.revokeObjectURL(url);
  }, [output]);

  const loadTemplate = useCallback((template: "allow-all" | "block-all" | "common") => {
    if (template === "allow-all") {
      setRules([{ id: "1", userAgent: "*", allow: ["/"], disallow: [] }]);
    } else if (template === "block-all") {
      setRules([{ id: "1", userAgent: "*", allow: [], disallow: ["/"] }]);
    } else if (template === "common") {
      setRules([
        { id: "1", userAgent: "*", allow: [], disallow: ["/admin/", "/private/", "/tmp/"] }
      ]);
    }
  }, []);

  return (
    <div className="space-y-4">
      {/* Templates */}
      <div className="flex flex-wrap gap-2">
        <span className="text-sm text-muted-foreground">{toolT.templates}:</span>
        <Button onClick={() => loadTemplate("allow-all")} size="sm" variant="outline">
          {toolT.allowAll}
        </Button>
        <Button onClick={() => loadTemplate("block-all")} size="sm" variant="outline">
          {toolT.blockAll}
        </Button>
        <Button onClick={() => loadTemplate("common")} size="sm" variant="outline">
          {toolT.commonRules}
        </Button>
      </div>

      {/* Rules */}
      <div className="space-y-3">
        {rules.map((rule, ruleIndex) => (
          <div key={rule.id} className="border border-border rounded-lg p-4 space-y-3 bg-muted/30">
            <div className="flex items-center gap-3">
              <div className="flex-1">
                <Label htmlFor={`ua-${rule.id}`} className="text-sm mb-1.5 block">
                  {toolT.userAgent}
                </Label>
                <Input
                  id={`ua-${rule.id}`}
                  value={rule.userAgent}
                  onChange={(e) => updateUserAgent(rule.id, e.target.value)}
                  placeholder="*"
                  className="text-sm"
                />
              </div>
              {rules.length > 1 && (
                <Button
                  onClick={() => removeRule(rule.id)}
                  size="sm"
                  variant="ghost"
                  className="mt-6"
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              )}
            </div>

            {/* Disallow */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label className="text-sm">{toolT.disallow}</Label>
                <Button
                  onClick={() => addPath(rule.id, "disallow")}
                  size="sm"
                  variant="outline"
                >
                  <Plus className="h-3 w-3 mr-1" />
                  {toolT.addPath}
                </Button>
              </div>
              {rule.disallow.map((path, pathIndex) => (
                <div key={pathIndex} className="flex items-center gap-2">
                  <Input
                    value={path}
                    onChange={(e) => updatePath(rule.id, "disallow", pathIndex, e.target.value)}
                    placeholder="/admin/"
                    className="text-sm flex-1"
                  />
                  <Button
                    onClick={() => removePath(rule.id, "disallow", pathIndex)}
                    size="sm"
                    variant="ghost"
                  >
                    <Trash2 className="h-3 w-3" />
                  </Button>
                </div>
              ))}
            </div>

            {/* Allow */}
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <Label className="text-sm">{toolT.allow}</Label>
                <Button
                  onClick={() => addPath(rule.id, "allow")}
                  size="sm"
                  variant="outline"
                >
                  <Plus className="h-3 w-3 mr-1" />
                  {toolT.addPath}
                </Button>
              </div>
              {rule.allow.map((path, pathIndex) => (
                <div key={pathIndex} className="flex items-center gap-2">
                  <Input
                    value={path}
                    onChange={(e) => updatePath(rule.id, "allow", pathIndex, e.target.value)}
                    placeholder="/public/"
                    className="text-sm flex-1"
                  />
                  <Button
                    onClick={() => removePath(rule.id, "allow", pathIndex)}
                    size="sm"
                    variant="ghost"
                  >
                    <Trash2 className="h-3 w-3" />
                  </Button>
                </div>
              ))}
            </div>
          </div>
        ))}

        <Button onClick={addRule} size="sm" variant="outline">
          <Plus className="h-4 w-4 mr-1" />
          {toolT.addRule}
        </Button>
      </div>

      {/* Additional Options */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
        <div>
          <Label htmlFor="sitemap" className="text-sm mb-1.5 block">
            {toolT.sitemapUrl}
          </Label>
          <Input
            id="sitemap"
            value={sitemap}
            onChange={(e) => setSitemap(e.target.value)}
            placeholder="https://example.com/sitemap.xml"
            className="text-sm"
          />
        </div>
        <div>
          <Label htmlFor="crawlDelay" className="text-sm mb-1.5 block">
            {toolT.crawlDelay}
          </Label>
          <Input
            id="crawlDelay"
            type="number"
            value={crawlDelay}
            onChange={(e) => setCrawlDelay(e.target.value)}
            placeholder="10"
            className="text-sm"
          />
        </div>
      </div>

      {/* Toolbar */}
      <div className="flex flex-col sm:flex-row flex-wrap items-start sm:items-center gap-3 border border-border rounded-lg px-3 py-2 bg-muted/30">
        <div className="flex items-center gap-2">
          <Button onClick={generateRobotsTxt} size="sm">
            {common.generate}
          </Button>
          {output && (
            <Button onClick={handleDownload} size="sm" variant="secondary">
              {common.download}
            </Button>
          )}
        </div>

        <div className="h-5 w-px bg-border hidden sm:block" />

        <Button onClick={handleClear} size="sm" variant="outline">
          {common.clear}
        </Button>
      </div>

      {/* Output */}
      {output && (
        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <label className="text-sm font-medium">{toolT.robotsTxtOutput}</label>
            <CopyButton
              text={output}
              copyLabel={common.copy}
              copiedLabel={common.copied}
            />
          </div>
          <Textarea
            value={output}
            readOnly
            className="font-mono text-sm min-h-[200px] sm:min-h-[400px] bg-muted/50"
          />
        </div>
      )}

      {/* Empty state */}
      {!output && (
        <div className="border border-dashed border-border rounded-lg p-12 text-center text-muted-foreground">
          <p className="text-sm">{common.outputPlaceholder}</p>
        </div>
      )}
    </div>
  );
}
